data/events.yml
=> Add whitby

data/events.yml
=> Added Chennai

source/layouts/layout.erb, source/start.html.erb
Fixed a couple of minor spelling mistakes.
=> Fix a couple of minor typos

source/start.html.erb
I was just reading through the `Starting` guide. Awesome stuff!
=> Fix some typos

data/events.yml
Hi @ashfurrow and peerlab.community! I would like to add our iOS peer lab meetup group to the community. Can I ask you to review this PR? Thanks 😃
=> Add San Francisco

data/events.yml
Hey Ash! Thanks for your work and we are always glad to see you at our Moscow meetings ;-)
=> Add a Moscow Peer Lab

data/events.yml
Adding one study group to the list, with schedule:
https://www.meetup.com/nyc-ios-study-group/
=> add iOS Study Group

data/events.yml
Got a basic website up and running on GitHub Pages.
=> Add Chicago meetup_url

data/events.yml
When I notice this idea about Peer Lab, I was very excited, I love the idea and people help each other,
I'm current study in MScMET School of Design PolyU, 
Within our program, we have people from different back ground, and I also want to extent the event to anyone who interested in this idea.
here is our [first event's link](https://meetmet-peerlab.github.io/peerlab/events/2017/02/02/Peer-Lab-Here-You-Are.html)
Hope everything goes well.
Cheers and thanks,
Victor Lee
=> Add new event in HK

data/events.yml
=> Add new city and country

data/events.yml
=> Add Copenhagen event

data/events.yml
=> Add Berlin peer lab @ SoundCloud

data/events.yml
Thank you for all of your help, folks! We're very excited and hope you will stop by in Berlin at some point and say hello 👋 There's always a place to hang out and crash here 🎉
=> Peer Lab Berlin meetup_url added 🥁🥁🥁

README.md, Rakefile, data/events.yml, source/find.html.erb
Improves getting set up docs, and adds support for multi twitters.
=> Multiple twitter handles

data/events.yml
Hi. We've moved 2 doors down. I'm glad I remembered to update this repo as well.  Thanks!
=> Change address of Chicago Meetup

.gitignore, data/events.yml, source/find.html.erb
I added Rostov-on-Don Peer Lab Community, and add new key "telegram_channel" for Telegram group.
=> Add Rostov Peer Lab community info

data/events.yml
New bigger Starbucks 😅 and also change in schedule
=> New bigger Starbucks 😅

data/events.yml
=> Updated Chennai address

data/events.yml
Hi Ash, I'm starting up a Manchester Peer Lab.
=> Add Manchester Peer Lab

data/events.yml
Hey there!
I've been thinking in this for months but I'm finally starting an iOS Peer Lab in Porto, Portugal.
It will happen every alternate Saturday mornings.
Thanks for the idea!
=> Adding Porto Peer Lab

data/events.yml
Hi. 
I would like to announce the Peer Lab Kyiv #Java
=> Add Peer Lab Kyiv #Java

data/events.yml
Hello world!
i wanna register meetups of native developers in Kyiv, Ukraine.
additional description of our community:
-> name  **PeerLab Kyiv #NativeDev**
-> target audience: C/C++/Rust developers
-> founded in December 2017
-> we post announcements on Ukraine locale IT resource [dou.ua](https://dou.ua) :  [example](https://dou.ua/calendar/23129/)
-> our telegram channel: https://t.me/peerlab_NativeDev
-> total number of telegram group members: 86
=> Register meetups for C/C++/Rust in Kyiv,Ukraine

data/events.yml
Adding Detroit's Swift peer lab!
=> added detroit swift peer lab

data/events.yml
Hey there!
We've been making these events for one year. We discuss mainly topics related to soft skills, helping each other.
=> Added Moscow psypeerlabforit

data/events.yml
Hello,
We are starting to cooperate as a Kharkiv iOS Peerlab. Our main goal is the exchange of experience and the development iOS community of the city.
Thanks,
Ivan
=> Add Kharkiv iOS Peerlab

data/events.yml
Hi! Happy to be a part of Peerlab community!
=> Add Moscow Devleads Peerlab

data/events.yml
Hello,
We moved from bar to coworking and changed meeting time to 11 a.m.
Thanks,
Ivan
=> Updated Kharkiv peerlab time and place

.travis.yml, Dangerfile, Gemfile, Gemfile.lock, Rakefile, data/events.yml
Fixes #77. Fixes #75.
This is a WIP because I haven't sorted the events yaml yet. My plan is to add a Rake task to do automatically and ask people to do that in the Danger failure message.
=> Adds Danger and check for sorted events.yml, and sorts events.yml

data/events.yml
Thanks for setting up and hosting this site for the community. Very much appreciated 🙏
=> Adding the Sydney Swift Peer Lab event 🐨

data/events.yml
Hello,
I've fixed titles for this peer lab.
Thanks
=> Fix missed titles

data/events.yml
Thanks, for peer lab  community
=> Update events.yml request from PeerLab Kyiv #Native Developers

source/start.html.erb
This has worked well-enough for us that I want to include it as a suggestion for other peer labs.
=> Adds standup instructions

data/events.yml
We have moved to the new location after the co-working closing
=> [UPD] (Kharkiv, Ukraine): location has been changed

data/events.yml
=> Update events.yml for Kyiv.

data/events.yml
👋  Hey, I'm going to start Yerevan's Peer Lab.
Previously I have been attending Saint-Petersburg's Peer Lab)
=> Add Yerevan's Peer Lab
